version: '3.7'

services:
  movie_service:
    build: ./movie-service
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8080
    volumes:
      - ./movie-service/:/app/
    ports:
      - '8001:8080'
    environment:
      - DATABASE_URI=mysql://movie_db_username:movie_db_password@movie_db/movie_db_dev
      - CAST_SERVICE_HOST_URL=http://cast_service:8000/api/v1/casts/

  movie_db:
    image: mysql:8.0.28
    volumes:
      - mysql_data_movie:/var/lib/mysql/data/
    environment:
      - MYSQL_USER=movie_db_username
      - MYSQL_PASSWORD=movie_db_password
      - MYSQL_DB=movie_db_dev

  cast_service:
    build: ./cast-service
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8080
    volumes:
      - ./cast-service/:/app/
    ports:
      - '8002:8080'
    environment:
      - DATABASE_URI=mysql://cast_db_username:cast_db_password@cast_db/cast_db_dev

  cast_db:
    image: mysql:8.0.28
    volumes:
      - mysql_data_movie:/var/lib/mysql/data/
    environment:
      - MYSQL_USER=cast_db_username
      - MYSQL_PASSWORD=cast_db_password
      - MYSQL_DB=cast_db_dev

  nginx:
    image: nginx:lastest
    ports:
      - '8080:8080'
    volumes:
      - ./nginx_config.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - cast_service
      - movie_service

volumes:
  mysql_data_movie:
  mysql_data_cast: